Test framework and a small set of basic tests
troglobit/finit pull request #158
Opened 2021-02-27 17:49 UTC by jackuess

2021-02-27 21:06 UTC, troglobit requested changes
Wow, this is just fantastic work, @jackuess! You and @magnusmalm have really added a huge amount of value to the project!

I've reviewed all the files, and all the changes.  The cleanup in the last couple of days is just astonishing. Very clean and succinct!

Only comment I have is that I think you should take pride in this and sign your work.  Add copyright and license headers to the top of the (relevant) files, or at least for the framework itself.  We can definitely reuse a lot of this in other projects, and also inside Westermo, but you really deserve the credit then.

2021-02-27 21:52 UTC, troglobit commented
@jackuess @magnusmalm  Oh, and add yourselves to the AUTHORS file, next to Jonas and Mattias :-)

2021-02-27 22:44 UTC, jackuess commented
Big thanks for the kind words and encouragement @troglobit - means a lot!

I've added license, copyright where I thought it was relevant, and appended myself to the contributors list now. I'll let @magnusmalm do the same himself :-)

2021-02-28 21:40 UTC, troglobit approved these changes

2021-02-28 21:40 UTC, merged