fstab with UUID/LABEL: nofail handling for fsck
troglobit/finit pull request #422
Opened 2024-12-17 22:10 UTC by az143

fix for #421: add support for 'nofail' fstab option. if present, finit's fsck invocation ignores errors for this device.

this is useful if you have an fstab entry for a device with UUID= or LABEL= which isn't always present and which you'd like to not  bail on (so you set nofail). in this case finit leaves the presence-or-not decision to fsck, which exits nonzero.

for block devices that are directly listed in fstab this change isn't important, because for such finit looks for the blockdev's existence and skips the fsck if n/a.

2024-12-18 08:53 UTC, troglobit requested changes
Nice catch, and thank you for the PR!  Only a small mistake in the patch.

2024-12-18 08:53 UTC, troglobit commented on src/finit.c
> +                        	logit(LOG_CONSOLE | LOG_WARNING, "Ignoring failed fsck % because of nofail option", dev);
Malformed format specifier, s/%/%s/

2024-12-18 09:13 UTC, az143 commented
On Wed, 18 Dec 2024 00:53:58 -0800, Joachim Wiberg writes:
>Nice catch, and thank you for the PR!  Only a small mistake in the patch.

ooops, sorry about that. patch patched...*sigh*


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + https://snafu.priv.at/
"Opinions are like assholes, I'll let you know when I want yours."
 -- David Cross and/or Bob Odenkirk

2024-12-18 12:32 UTC, troglobit commented
> On Wed, 18 Dec 2024 00:53:58 -0800, Joachim Wiberg writes:
> Nice catch, and thank you for the PR! Only a small mistake in the patch.
> ooops, sorry about that. patch patched...*sigh*
> […](#)
> -- Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + https://snafu.priv.at/ "Opinions are like assholes, I'll let you know when I want yours." -- David Cross and/or Bob Odenkirk

No worries, happens to the best of us :smiley: 

Please rebase, squash, and force-push your branch.

2024-12-19 23:15 UTC, az143 commented
squashed and pushed

2024-12-20 00:48 UTC, troglobit approved these changes
👍

2024-12-20 01:18 UTC, merged